const IMAGES = {
    LOAD: 'IMAGES_LOAD',
    LOAD_SUCCESS: 'IMAGES_LOAD_SUCCESS',
    LOAD_ERROR: 'IMAGES_LOAD_ERROR'
}

const STATS = {
    LOAD: 'STATS_LOAD',
    LOAD_SUCCESS: 'STATS_LOAD_SUCCESS',
    LOAD_ERROR: 'STATS_LOAD_ERROR'
}
export { IMAGES, STATS }